# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Place.create(city: '北海道')
Place.create(city: '青森県')
Place.create(city: '岩手県')
Place.create(city: '宮城県')
Place.create(city: '秋田県')
Place.create(city: '山形県')
Place.create(city: '福島県')
Place.create(city: '茨城県')
Place.create(city: '栃木県')
Place.create(city: '群馬県')
Place.create(city: '埼玉県')
Place.create(city: '千葉県')
Place.create(city: '東京都')
Place.create(city: '神奈川県')
Place.create(city: '新潟県')
Place.create(city: '富山県')
Place.create(city: '石川県')
Place.create(city: '福井県')
Place.create(city: '山梨県')
Place.create(city: '長野県')
Place.create(city: '岐阜県')
Place.create(city: '静岡県')
Place.create(city: '愛知県')
Place.create(city: '三重県')
Place.create(city: '滋賀県')
Place.create(city: '京都府')
Place.create(city: '大阪府')
Place.create(city: '兵庫県')
Place.create(city: '奈良県')
Place.create(city: '和歌山県')
Place.create(city: '鳥取県')
Place.create(city: '島根県')
Place.create(city: '岡山県')
Place.create(city: '広島県')
Place.create(city: '山口県')
Place.create(city: '徳島県')
Place.create(city: '香川県')
Place.create(city: '愛媛県')
Place.create(city: '高知県')
Place.create(city: '福岡県')
Place.create(city: '佐賀県')
Place.create(city: '長崎県')
Place.create(city: '熊本県')
Place.create(city: '大分県')
Place.create(city: '宮崎県')
Place.create(city: '鹿児島県')
Place.create(city: '沖縄県')

